config/routes.rb
Rails.application.routes.draw do
  resources :testqs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/testq.rb
class Testq < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/testqs_controller.rb
class TestqsController < ApplicationController
  before_action :set_testq, only: %i[ show edit update destroy ]

  # GET /testqs or /testqs.json
  def index
    @testqs = Testq.all
  end

  # GET /testqs/1 or /testqs/1.json
  def show
  end

  # GET /testqs/new
  def new
    @testq = Testq.new
  end

  # GET /testqs/1/edit
  def edit
  end

  # POST /testqs or /testqs.json
  def create
    @testq = Testq.new(testq_params)
    respond_to do |format|
      if @testq.save
        format.html { redirect_to testq_url(@testq), notice: "Testq was successfully created." }
        format.json { render :show, status: :created, location: @testq }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @testq.errors, status: :unprocessable_entity }
      end
    end

    testq_params['countq'].to_i.times do |x|
      Resque.enqueue(SimpleJob, [@testq.id, x] )
    end

  end


  def update
    respond_to do |format|
      if @testq.update(testq_params)
        format.html { redirect_to testq_url(@testq), notice: "Testq was successfully updated." }
        format.json { render :show, status: :ok, location: @testq }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @testq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testqs/1 or /testqs/1.json
  def destroy
    @testq.destroy

    respond_to do |format|
      format.html { redirect_to testqs_url, notice: "Testq was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testq
      @testq = Testq.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def testq_params
      params.require(:testq).permit(:countq, :nowq, :commentq)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/testqs_helper.rb
module TestqsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resqueruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/testqs/_form.html.erb
<%= form_with(model: testq) do |form| %>
  <% if testq.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(testq.errors.count, "error") %> prohibited this testq from being saved:</h2>

      <ul>
        <% testq.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :countq, style: "display: block" %>
    <%= form.number_field :countq %>
  </div>

  <div>
    <%= form.label :nowq, style: "display: block" %>
    <%= form.number_field :nowq %>
  </div>

  <div>
    <%= form.label :commentq, style: "display: block" %>
    <%= form.text_field :commentq %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/testqs/_testq.html.erb
<div id="<%= dom_id testq %>">
  <p>
    <strong>Countq:</strong>
    <%= testq.countq %>
  </p>

  <p>
    <strong>Nowq:</strong>
    <%= testq.nowq %>
  </p>

  <p>
    <strong>Commentq:</strong>
    <%= testq.commentq %>
  </p>

</div>

app/views/testqs/edit.html.erb
<h1>Editing testq</h1>

<%= render "form", testq: @testq %>

<br>

<div>
  <%= link_to "Show this testq", @testq %> |
  <%= link_to "Back to testqs", testqs_path %>
</div>

app/views/testqs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Testqs</h1>

<div id="testqs">
  <% @testqs.each do |testq| %>
    <%= render testq %>
    <p>
      <%= link_to "Show this testq", testq %>
    </p>
  <% end %>
</div>

<%= link_to "New testq", new_testq_path %>

app/views/testqs/new.html.erb
<h1>New testq</h1>

<%= render "form", testq: @testq %>

<br>

<div>
  <%= link_to "Back to testqs", testqs_path %>
</div>

app/views/testqs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @testq %>

<div>
  <%= link_to "Edit this testq", edit_testq_path(@testq) %> |
  <%= link_to "Back to testqs", testqs_path %>

  <%= button_to "Destroy this testq", @testq, method: :delete %>
</div>